import { Animal } from "@/types/animal";

export const mockAnimals: Animal[] = [
  { id: 1, name: "Bella", species: "Dog", breed: "Golden Retriever", age: 24, gender: "Female", color: "Golden", weight: 25.4, status: "Available", description: "Friendly, playful, loves children and park walks.", imageUrl: "https://placedog.net/600/420?id=11", healthNotes: "Vaccinated, dewormed, microchipped", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 2, name: "Max", species: "Dog", breed: "Labrador Mix", age: 36, gender: "Male", color: "Black", weight: 29.1, status: "Pending", description: "Gentle and patient with families and other pets.", imageUrl: "https://placedog.net/600/420?id=12", healthNotes: "Vaccinated, neutered", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 3, name: "Luna", species: "Cat", breed: "Domestic Shorthair", age: 14, gender: "Female", color: "Gray", weight: 4.2, status: "Available", description: "Curious and affectionate cat who loves sunbathing.", imageUrl: "https://placekitten.com/600/421", healthNotes: "Vaccinated, litter trained", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 4, name: "Charlie", species: "Dog", breed: "Beagle", age: 20, gender: "Male", color: "Tri-color", weight: 13.5, status: "Adopted", description: "Cheerful beagle with high energy and a sweet nature.", imageUrl: "https://placedog.net/600/420?id=13", healthNotes: "Vaccinated", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 5, name: "Milo", species: "Cat", breed: "Tabby", age: 10, gender: "Male", color: "Orange", weight: 3.8, status: "Available", description: "Playful and social, enjoys wand toys and cuddles.", imageUrl: "https://placekitten.com/600/422", healthNotes: "Vaccinated, flea treated", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 6, name: "Daisy", species: "Rabbit", breed: "Holland Lop", age: 8, gender: "Female", color: "White", weight: 1.9, status: "Available", description: "Calm bunny that likes quiet spaces and fresh greens.", imageUrl: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=900&q=80", healthNotes: "Healthy, regular checkups", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 7, name: "Rocky", species: "Dog", breed: "German Shepherd", age: 30, gender: "Male", color: "Brown/Black", weight: 32.7, status: "Pending", description: "Loyal companion with basic obedience training.", imageUrl: "https://placedog.net/600/420?id=14", healthNotes: "Vaccinated, microchipped", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 8, name: "Coco", species: "Bird", breed: "Cockatiel", age: 18, gender: "Female", color: "Yellow/Gray", weight: 0.09, status: "Available", description: "Social little bird that chirps happily every morning.", imageUrl: "https://images.unsplash.com/photo-1444464666168-49d633b86797?auto=format&fit=crop&w=900&q=80", healthNotes: "Healthy wings and diet", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 9, name: "Oliver", species: "Cat", breed: "Siamese Mix", age: 16, gender: "Male", color: "Cream/Brown", weight: 4.5, status: "Available", description: "Sweet and talkative cat that follows people around.", imageUrl: "https://placekitten.com/600/423", healthNotes: "Vaccinated, neutered", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 10, name: "Nala", species: "Dog", breed: "Corgi", age: 26, gender: "Female", color: "Tan/White", weight: 11.2, status: "Adopted", description: "Happy and energetic, loves playing fetch indoors.", imageUrl: "https://placedog.net/600/420?id=15", healthNotes: "Vaccinated", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 11, name: "Simba", species: "Cat", breed: "Maine Coon Mix", age: 22, gender: "Male", color: "Brown", weight: 5.6, status: "Pending", description: "Confident and fluffy companion with a gentle temperament.", imageUrl: "https://placekitten.com/600/424", healthNotes: "Vaccinated, dewormed", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: 12, name: "Poppy", species: "Rabbit", breed: "Mini Rex", age: 12, gender: "Female", color: "Chocolate", weight: 2.3, status: "Available", description: "Cuddly rabbit that bonds quickly with patient owners.", imageUrl: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=900&q=80", healthNotes: "Healthy coat and teeth", arrivalDate: new Date().toISOString(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
];
